ifneq ($(filter m y,$(CONFIG_ATL_4000MAH_8A_BATTERY_PROFILE)),)
	ccflags-y += -DATL_4000MAH_8A_BATTERY_PROFILE
endif
ifneq ($(filter m y,$(CONFIG_SCUD_4000MAH_8A_BATTERY_PROFILE)),)
	ccflags-y += -DSCUD_4000MAH_8A_BATTERY_PROFILE
endif
ifneq ($(filter m y,$(CONFIG_ATL_LS40_1545MAH_BATTERY_PROFILE)),)
	ccflags-y += -DATL_LS40_1545MAH_BATTERY_PROFILE
endif
ifneq ($(filter m y,$(CONFIG_ATL_LS30_1255MAH_BATTERY_PROFILE)),)
	ccflags-y += -DATL_LS30_1255MAH_BATTERY_PROFILE
endif
ifneq ($(filter m y,$(CONFIG_ATL_NM40_712MAH_BATTERY_PROFILE)),)
	ccflags-y += -DATL_NM40_712MAH_BATTERY_PROFILE
endif

obj-m += bq27426_fg_mmi.o
