ifneq ($(filter m y,$(CONFIG_INPUT_AWINIC_HAPTIC)),)
	ccflags-y += -DCONFIG_INPUT_AWINIC_HAPTIC
endif
ifneq ($(filter m y,$(CONFIG_SMITH_DTB)),)
	ccflags-y += -DCONFIG_AW8697_BOOT_VIBRATION
endif

obj-$(CONFIG_AW8697_HAPTIC) += aw8697.o
