obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/

obj-$(CONFIG_P938X_CHARGER)	+= p938x_charger/
obj-$(CONFIG_QPNP_ADAPTIVE_CHARGE) += qpnp_adaptive_charge/
obj-$(CONFIG_QPNP_SMBCHARGER_MMI) += qpnp-smbcharger-mmi/
