ifneq ($(filter m y,$(CONFIG_RACER_DTB)),)
    ccflags-y += -DCONFIG_DRM_DYNAMIC_REFRESH_RATE
endif

ifneq ($(filter m y,$(CONFIG_BURTON_DTB)),)
    ccflags-y += -DCONFIG_DRM_DYNAMIC_REFRESH_RATE
endif

obj-m := sec_mmi.o
sec_mmi-objs = sec_ts.o sec_ts_fn.o sec_ts_fw.o sec_cmd.o sec_ts_only_vendor.o

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
    ccflags-y += -DCONFIG_INPUT_TOUCHSCREEN_MMI -DCONFIG_PM
    ifneq ($(filter m y, $(CONFIG_DRM_PANEL_NOTIFICATIONS)),)
        ccflags-y += -DCONFIG_DRM_PANEL_NOTIFICATIONS
    endif
    ifneq ($(filter m y, $(CONFIG_PANEL_NOTIFICATIONS)),)
        ccflags-y += -DCONFIG_PANEL_NOTIFICATIONS
    endif

    sec_mmi-objs += sec_ts_mmi_class.o
else
    sec_mmi-objs += sec_ts_mmi.o
endif
