ccflags-$(CONFIG_RACER_DTB) += -DCONFIG_DRM_DYNAMIC_REFRESH_RATE
ccflags-$(CONFIG_BURTON_DTB) += -DCONFIG_DRM_DYNAMIC_REFRESH_RATE

obj-m := sec_mmi.o
sec_mmi-objs = sec_ts.o sec_ts_fn.o sec_ts_fw.o sec_cmd.o sec_ts_only_vendor.o

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
    ccflags-y += -DCONFIG_INPUT_TOUCHSCREEN_MMI -DCONFIG_PM
    ccflags-$(CONFIG_DRM_PANEL_NOTIFICATIONS) += -DCONFIG_DRM_PANEL_NOTIFICATIONS
    ccflags-$(CONFIG_PANEL_NOTIFICATIONS) += -DCONFIG_PANEL_NOTIFICATIONS

    sec_mmi-objs += sec_ts_mmi_class.o
else
    sec_mmi-objs += sec_ts_mmi.o
endif
