ccflags-$(CONFIG_INPUT_TOUCHSCREEN_MMI) += -DCONFIG_INPUT_TOUCHSCREEN_MMI
ccflags-$(CONFIG_DRM_PANEL_NOTIFICATIONS) += -DCONFIG_DRM_PANEL_NOTIFICATIONS

synaptics_mmi_class-objs += synaptics_dsx_i2c.o synaptics_dsx_mmi.o synaptics_dsx_instance.o

obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_MMI_CLASS_CORE) += synaptics_mmi_class.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_MMI_CLASS_FW_UPDATE) += synaptics_mmi_class_fw_update.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_MMI_CLASS_RMI_DEV) += synaptics_mmi_class_rmi_dev.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_MMI_CLASS_TEST_REPORTING) += synaptics_mmi_class_test_reporting.o
