# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(TOP)/vendor/qcom/opensource/audio-kernel/include
EXTRA_CFLAGS += -I$(TOP)/vendor/qcom/opensource/audio-kernel/include/uapi/

ifneq (,$(filter nio%, $(TARGET_PRODUCT)))
EXTRA_CFLAGS += -DCONFIG_AW882XX_CODEC
endif

aw882xx_k419-objs = aw882xx.o
obj-m += aw882xx_k419.o
