obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_MMI_CORE) += synaptics_core_module.o

synaptics_core_module-objs := synaptics_core.o synaptics_touch.o
ccflags-$(CONFIG_DRM_PANEL_NOTIFICATIONS) += -DCONFIG_DRM_PANEL_NOTIFICATIONS

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
	ccflags-y += -DCONFIG_INPUT_TOUCHSCREEN_MMI
	synaptics_core_module-objs += synaptics_ts_mmi.o
endif
